import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import {
  HelpCircle,
  Phone,
  BarChart3,
  Users,
  Building,
  Settings,
} from "lucide-react";
import { Link } from "react-router-dom";
import NortherLeadsVideo from "@/assets/trueNorthVideo.mp4";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const PPCFaqs = () => {
  const faqs = [
    {
      id: "faq-1",
      question: "What is a Pay Per Call network?",
      answer:
        "A pay per call network, also known as a pay per call agency, is a company that focuses primarily on marketing that is intended to generate an inbound phone call. Publishers, or affiliates, work with a pay per call network to gain access to pay per call affiliate offers. Advertisers, or merchants, work with pay per call networks to generate more phone calls for their business.",
    },
    {
      id: "faq-2",
      question: "How Does Pay Per Call Work?",
      answer:
        "Pay per call works simply by arranging the business relationship between the marketer and the client around a phone call, rather than a click or online sales like most digital marketing agencies or affiliate networks operate. The most common method is where advertisers pay affiliates a pre-arranged amount for every phone call generated by their marketing efforts.",
    },
    {
      id: "faq-3",
      question: "What Industries Work Well in Pay Per Call?",
      answer:
        "Any business that is reliant on speaking with a customer before providing their product or service is a perfect fit for pay per call. The legal industry works very well in pay per call as attorneys often need to consult with their clients prior to agreeing to a working relationship. As well, local home contractors work very well with pay per call as a majority of the work they provide are for emergencies and require immediate assistance, which a phone call solves.",
    },
    {
      id: "faq-4",
      question: "How is Pay Per Call Tracked?",
      answer:
        "Pay per call is tracked using unique telephone numbers, also known as direct inward dialling numbers (DID). The unique DID can be tracked back to the original source of the phone call, allowing the user to measure the effectiveness of their marketing and attribute sales, and or, revenue to the appropriate parties. Often times a call tracking solution is utilized for this purpose or a user can create their own call tracking system.",
    },
    {
      id: "faq-5",
      question: "What Role Does a Pay Per Call Network Play?",
      answer:
        "A good pay per call agency or pay per call network plays a crucial role in growing a pay per call business. Often times, advertisers are not capable of growing an affiliate program so they work with a network to plug into a large, diverse network of marketers that can aid in growth. Publishers are able to gain value by accessing pay per call offers that may be difficult to obtain on their own. The pay per call network can be viewed as an extension to any business or company by performing sales, accounting, business development, quality assurance, lines of credit and so on.",
    },
    {
      id: "faq-6",
      question: "What are the Benefits of Pay Per Call Marketing?",
      answer:
        "Pay per call marketing offers several key benefits: higher conversion rates as phone leads typically convert better than web leads, immediate customer interaction allowing for real-time objection handling, better lead quality as calling prospects show higher intent, easier tracking and attribution, and the ability to provide personalized service that builds trust and rapport with potential customers.",
    },
    {
      id: "faq-7",
      question: "How Much Does Pay Per Call Cost?",
      answer:
        "Pay per call costs vary significantly based on industry, competition, call quality requirements, and geographic targeting. Costs can range from $10-$500+ per qualified call depending on the vertical. Legal and financial services typically command higher prices due to higher lifetime customer value, while home services might be more affordable. The key is focusing on ROI rather than just cost per call.",
    },
    {
      id: "faq-8",
      question: "How Do You Ensure Call Quality?",
      answer:
        "Call quality is ensured through multiple layers: pre-call qualification using interactive voice response (IVR) systems, real-time call monitoring and scoring, post-call verification processes, detailed call recording and analysis, strict publisher vetting and ongoing performance monitoring, and continuous optimization based on conversion data and feedback from advertisers.",
    },
    {
      id: "faq-9",
      question:
        "What Makes Northern Leads Media Different from Other Networks?",
      answer:
        "Northern Leads Media stands out through our exclusive focus on quality over quantity, transparent reporting and real-time analytics, dedicated account management and support, proprietary fraud detection systems, industry-leading compliance standards, flexible payment terms, and our commitment to long-term partnerships rather than transactional relationships. We view ourselves as an extension of your business, not just a vendor.",
    },
  ];

  const benefits = [
    {
      icon: Phone,
      title: "Higher Conversion Rates",
      description:
        "Phone leads convert 5-10x better than web leads due to immediate personal interaction.",
    },
    {
      icon: BarChart3,
      title: "Better ROI Tracking",
      description:
        "Precise attribution and real-time analytics help optimize campaign performance.",
    },
    {
      icon: Users,
      title: "Quality Leads",
      description:
        "Callers demonstrate higher intent and are more likely to convert into customers.",
    },
    {
      icon: Building,
      title: "Industry Expertise",
      description:
        "Specialized knowledge across multiple verticals ensures campaign success.",
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <main>
        {/* Hero Section */}
        <section className="relative py-24 bg-hero-gradient overflow-hidden">
          {/* Video Background */}
          <video
            autoPlay
            muted
            loop
            playsInline
            className="absolute inset-0 w-full h-full object-cover"
          >
            <source src={NortherLeadsVideo} type="video/mp4" />
          </video>
          <div className="absolute inset-0 bg-hero-gradient opacity-60" />
          <div className="absolute inset-0 overflow-hidden">
            <svg
              className="absolute bottom-0 w-full h-32 text-surface-elevated opacity-20"
              viewBox="0 0 1200 120"
              preserveAspectRatio="none"
              fill="currentColor"
            >
              <path d="M0,60 C300,100 600,20 900,60 C1050,80 1150,40 1200,60 L1200,120 L0,120 Z" />
            </svg>
          </div>

          <div className="relative z-10 container mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <div className="w-20 h-20 mx-auto mb-6 rounded-full bg-accent/20 flex items-center justify-center">
              <HelpCircle className="w-10 h-10 text-accent" />
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-heading font-bold text-foreground mb-6 leading-tight">
              Pay Per Call{" "}
              <span className="bg-gradient-to-r from-accent to-accent-glow-light bg-clip-text text-transparent">
                FAQ
              </span>
            </h1>
            <p className="text-lg sm:text-xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
              Everything you need to know about pay per call marketing,
              networks, and how Northern Leads Media can help your business
              grow.
            </p>
          </div>
        </section>

        {/* Benefits Overview */}
        <section className="py-16 bg-surface-subtle">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              {benefits.map((benefit, index) => {
                const IconComponent = benefit.icon;
                return (
                  <Card
                    key={index}
                    className="p-6 text-center bg-surface-elevated border-border hover:border-accent/30 transition-all duration-300 group"
                  >
                    <div className="w-12 h-12 mx-auto mb-4 rounded-xl bg-accent/10 flex items-center justify-center group-hover:bg-accent/20 transition-colors">
                      <IconComponent className="w-6 h-6 text-accent" />
                    </div>
                    <h3 className="font-heading font-semibold text-foreground mb-2 group-hover:text-accent transition-colors">
                      {benefit.title}
                    </h3>
                    <p className="text-muted-foreground text-sm leading-relaxed">
                      {benefit.description}
                    </p>
                  </Card>
                );
              })}
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="py-24 bg-background">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto">
              <div className="text-center mb-16">
                <p className="text-accent font-medium uppercase tracking-wide text-sm mb-4">
                  Pay Per Call FAQ
                </p>
                <h2 className="text-3xl sm:text-4xl font-heading font-bold text-foreground mb-8">
                  Frequently Asked Questions
                </h2>
                <p className="text-lg text-muted-foreground">
                  Get answers to the most common questions about pay per call
                  marketing and how it can benefit your business.
                </p>
              </div>

              <Card className="p-8 bg-surface-elevated border-border">
                <Accordion type="single" collapsible className="w-full">
                  {faqs.map((faq, index) => (
                    <AccordionItem
                      key={faq.id}
                      value={faq.id}
                      className="border-border"
                    >
                      <AccordionTrigger className="text-left text-foreground hover:text-accent transition-colors font-semibold">
                        {faq.question}
                      </AccordionTrigger>
                      <AccordionContent className="text-muted-foreground leading-relaxed pt-4">
                        {faq.answer}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </Card>
            </div>
          </div>
        </section>

        {/* Additional Resources */}
        <section className="py-16 bg-surface-subtle">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-12">
              <h2 className="text-2xl font-heading font-bold text-foreground mb-4">
                Still Have Questions?
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Our team of pay per call experts is here to help you understand
                how our platform can drive growth for your business.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
              <Card className="p-6 text-center bg-surface-elevated border-border hover:border-accent/30 transition-all duration-300">
                <Phone className="w-12 h-12 mx-auto mb-4 text-accent" />
                <h3 className="font-semibold text-foreground mb-2">
                  Talk to an Expert
                </h3>
                <p className="text-muted-foreground text-sm mb-4">
                  Schedule a call with our team to discuss your specific needs.
                </p>
                <Button variant="nav" size="sm" className="w-full">
                  Schedule Call
                </Button>
              </Card>

              <Card className="p-6 text-center bg-surface-elevated border-border hover:border-accent/30 transition-all duration-300">
                <Settings className="w-12 h-12 mx-auto mb-4 text-accent" />
                <h3 className="font-semibold text-foreground mb-2">
                  Live Demo
                </h3>
                <p className="text-muted-foreground text-sm mb-4">
                  See our platform in action with a personalized demo.
                </p>
                <Button
                  variant="default"
                  size="sm"
                  className="w-full bg-orange-500 hover:bg-orange-600 text-white border-0 font-medium transition-all duration-300 hover:scale-105 shadow-lg hover:shadow-xl"
                  asChild
                >
                  <Link to="/contact">Request Demo</Link>
                </Button>
              </Card>

              <Card className="p-6 text-center bg-surface-elevated border-border hover:border-accent/30 transition-all duration-300">
                <HelpCircle className="w-12 h-12 mx-auto mb-4 text-accent" />
                <h3 className="font-semibold text-foreground mb-2">
                  Support Center
                </h3>
                <p className="text-muted-foreground text-sm mb-4">
                  Access our knowledge base and get instant answers.
                </p>
                <Button
                  variant="default"
                  size="sm"
                  className="w-full bg-orange-500 hover:bg-orange-600 text-white border-0 font-medium transition-all duration-300 hover:scale-105 shadow-lg hover:shadow-xl"
                  asChild
                >
                  <Link to="/contact">Visit Help Center</Link>
                </Button>
              </Card>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-24 bg-background">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <Card className="max-w-4xl mx-auto p-12 text-center bg-gradient-to-r from-surface-elevated to-surface-subtle border-accent/20">
              <Phone className="w-16 h-16 mx-auto mb-6 text-accent" />
              <h2 className="text-3xl font-heading font-bold text-foreground mb-6">
                Ready to Start Generating Quality Calls?
              </h2>
              <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
                Join thousands of businesses that trust Northern Leads Media to
                deliver high-quality phone leads and drive sustainable growth.
              </p>
              <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                <Button
                  variant="default"
                  size="xl"
                  className="bg-orange-500 hover:bg-orange-600 text-white border-0 font-semibold tracking-wide transition-all duration-300 hover:scale-105 shadow-lg hover:shadow-xl"
                  asChild
                >
                  <Link to="/contact">Get Started Today</Link>
                </Button>
              </div>
            </Card>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default PPCFaqs;
